# This file contains values from Cookiecutter

default_context:
  project_name: "phdbot"
  project_description: "Awesome `phdbot` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "phdbot"
  license: "BSD-3"
  minimal_python_version: 3.8
  github_name: "phdbot"
  email: "domi@phdbot.cloud"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
